glider_node:
  ros__parameters:
    publishers:
      rate: 0.0
      nav_sat_fix: true
      utm_zone: "18S"   # Pennovation : 18S, College station : 14R
      map_frame: "map"
      odom_frame: "rko_odom"
      base_link_frame: "base_link"
      viz:
        use: true
        origin_easting: 753912.0063845584   # These needs to be changed based on the location
        origin_northing: 3385461.6073698294
    subscribers:
      use_odom: true
      dgps_topic: "/dgps/antenna1/fix"
