glider_node:
  ros__parameters:
    publishers:
      rate: 0.0
      nav_sat_fix: false
      viz:
        use: true
        origin_easting: 753912.0063845584
        origin_northing: 3385461.6073698294
    subscribers:
      use_odom: false
